[project]
name = "forestbot"
version = "2.0.0"
description = "Enables a Forest of MobileCoin enabled Signal bots"
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "Forest", email = "forest@mobilecoin.com" }]
requires-python = ">=3.11"
dependencies = [
    "asyncpg",
    "base58",
    "phonenumbers",
    "prometheus_async",
    "prometheus_client",
    "protobuf>=4.25",
    "ulid2",
    "pycryptodome",
    "aiohttp[speedups]>=3.11",
    "python-json-logger>=2.0.7",
]

[project.urls]
homepage = "https://github.com/i-infra/forestfire"

[dependency-groups]
dev = [
    "black>=24.1.1",
    "mypy",
    "pylint",
    "pytest",
    "pytest-cov",
    "pytest-asyncio",
    "types-protobuf>=4.25",
    "isort",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["forest", "mc_util"]

[tool.mypy]
ignore_missing_imports=true

disallow_untyped_calls=true
disallow_untyped_defs=true
disallow_untyped_decorators=true # eh
check_untyped_defs=true

warn_redundant_casts=true
warn_unused_ignores=true
warn_unused_configs=true

[tool.pylint.'MESSAGES CONTROL']

disable= [
    "attribute-defined-outside-init",
    "invalid-name",
    "missing-docstring",
    "protected-access",
    "too-few-public-methods",
    "too-many-instance-attributes",
    "logging-fstring-interpolation",
    "consider-using-with",
    "consider-using-from-import",
    "fixme",
    # "no-self-use",
    "unspecified-encoding",
    # handled by black
    "format",
    "line-too-long",
]

[tool.pylint.TYPECHECK]
ignored-classes="PrintableWrapper"

[tool.pylint.VARIABLES]
dummy-variables-rgx="(_|dummy|unused|i)"

[tool.pylint.SIMILARITY]
min-similarity-lines=9
ignore-imports="yes"


[tool.pytest.ini_options]
asyncio_mode = "strict"
